{% set name = "crest" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/crest-lab/{{ name }}.git
  git_tag: v{{ version }}
  git_depth: 1

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex
    - git submodule update --init
    - export FFLAGS="${FFLAGS} -ffree-line-length-none -DWITH_OPENBLAS"
    - |
      cmake ${CMAKE_ARGS} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DWITH_TESTS=OFF \
            -B build_dir \
            -GNinja
    - cmake --build build_dir
    - cmake --install build_dir

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - git
    - cmake
    - ninja
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - libopenblas
  host:
    - libblas
    - liblapack
    - libopenblas
  run:
    - xtb

test:
  commands:
    - crest --version

about:
  home: https://crest-lab.github.io/crest-docs/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'Conformer-Rotamer Ensemble Sampling Tool based on the xtb Semiempirical Extended Tight-Binding Program Package'
  description: |
    This is the official repository of the CREST. The program was
    originally developed by the Grimme group at the University of Bonn
    as is an extension to the xtb program to drive semiempirical quantum
    mechanical calculations for the exploration of chemical space.
    Since then several functionalities have been added to the code. 
    In its current state, the program provides a variety of sampling 
    procedures, for example for improved thermochemistry, or explicit solvation 
    and analysis of structure ensembles. 
  doc_url: https://crest-lab.github.io/crest-docs/
  dev_url: https://github.com/crest-lab/crest

extra:
  recipe-maintainers:
    - awvwgk
    - jan-janssen
