{% set name = "crest" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/crest-lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d908635472e8eaf04f6f535cb197ed7a6382196794f7e137cb7f47850fcf353d

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex
    - export FFLAGS="${FFLAGS} -ffree-line-length-none"
    - cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -B build_dir -GNinja
    - cmake --build build_dir
    - cmake --install build_dir
    - cd build_dir && make test
    # - mkdir -p $PREFIX/share/man/man1
    # - asciidoctor --attribute=release-version={{ version }} --backend=manpage --out-file=$PREFIX/share/man/man1/crest.1 docs/man/crest.adoc

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - asciidoctor
  host:
    - libblas
    - liblapack
    - tblite
  run:

test:
  commands:
    - crest --help

about:
  home: https://crest-lab.github.io/crest-docs/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'Conformer-Rotamer Ensemble Sampling Tool based on the xtb Semiempirical Extended Tight-Binding Program Package'
  description: |
    This is the offical repository of the crest program developed by the 
    Grimme group in Bonn. crest is an extension to the xtb program. It 
    functions as an IO based OMP scheduler (i.e., calculations are
    performed by the xtb program) and tool for the creation and
    analysation of structure ensembles. 
  doc_url: https://crest-lab.github.io/crest-docs/
  dev_url: https://github.com/crest-lab/crest

extra:
  recipe-maintainers:
    - awvwgk
    - jan-janssen
