{% set name = "crest" %}
{% set version = "2.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f17da872064eb64502ac24c19e431467940d98dcb1bd391f7267f412a0a79dab
  patches:
    - gcc.patch

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex
    - cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -B build_dir -GNinja
    - cmake --build build_dir
    - cmake --install build_dir
    - mkdir -p $PREFIX/share/man/man1
    - asciidoctor --attribute=release-version={{ version }} --backend=manpage --out-file=$PREFIX/share/man/man1/crest.1 docs/man/crest.adoc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - asciidoctor
  host:
    - libblas
    - liblapack
  run:
    - xtb

test:
  commands:
    - crest --help

about:
  home: https://xtb-docs.readthedocs.io/en/latest/crest.html
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'Conformer-Rotamer Ensemble Sampling Tool based on the xtb Semiempirical Extended Tight-Binding Program Package'
  description: |
    This is the offical repository of the crest program developed by the 
    Grimme group in Bonn. crest is an extension to the xtb program. It 
    functions as an IO based OMP scheduler (i.e., calculations are
    performed by the xtb program) and tool for the creation and
    analysation of structure ensembles. 
  doc_url: https://xtb-docs.readthedocs.io/en/latest/crest.html
  dev_url: https://github.com/grimme-lab/crest

extra:
  recipe-maintainers:
    - awvwgk
    - jan-janssen
