{% set name = "crest" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/crest-lab/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: f5d00d41c18a6f999ec8c890aa56d4b7ac8b1bf52a8c6d48c1d151c0126f7793

  - folder: subprojects/toml-f
    sha256: e66d0e355a8a2e65fd5fc7cd4f00078dfbdbf1b3cc47b60f028c19467df4c337
    url: https://github.com/toml-f/toml-f/archive/v0.4.2.tar.gz

  - folder: subprojects/gfnff
    sha256: b69d7b2b34778c3e732bb41d91b934628ccd9c6e15002092888df7778c8a501f
    url: https://github.com/pprcht/gfnff/archive/v0.0.1.tar.gz

  - folder: subprojects/gfn0
    sha256: d0f1fb0302a689a726632e2d2dcd740059e94882c70ca63a1c34c3e769a51ad4
    url: https://github.com/pprcht/gfn0/archive/v0.1.tar.gz

  - folder: subprojects/lwoniom
    sha256: cf76a8aa72aeba1ec8d8f0fe9f5cb4ce24c989e05ee6f3a775f7f17b8079f61c
    url: https://github.com/crest-lab/lwoniom/archive/v0.0.1.tar.gz

  - folder: subprojects/test-drive
    sha256: 46aa66cb3761eb7bb46563325c2a5b5f561f654cd9d8151487cd19be1f813370
    url: https://github.com/fortran-lang/test-drive/archive/482fc754e5573466962b9c887126829eb78f9f1a.tar.gz

  - folder: subprojects/tblite
    sha256: c65623e933581a05d781b91a50d92586f54cbb094f90646222f143952694f996
    url: https://github.com/pprcht/tblite/archive/v0.3.0-fork.tar.gz

  - folder: subprojects/tblite/subprojects/mctc-lib
    sha256: 03dc8ccba37413da70e55a07cef8e8de53bce33f5bb52c1f8db5fec326abe083
    url: https://github.com/grimme-lab/mctc-lib/archive/v0.3.1.tar.gz

  - folder: subprojects/tblite/subprojects/dftd4
    sha256: 0e3e8d5f9e9e5414b9979967c074c953706053832e551d922c27599e7324bace
    url: https://github.com/dftd4/dftd4/archive/v3.6.0.tar.gz

  - folder: subprojects/tblite/subprojects/dftd4/subprojects/mstore
    sha256: 56b3d778629eb74b8a515cd53c727d04609f858a07f8d3555fd5fd392a206dcc
    url: https://github.com/grimme-lab/mstore/archive/v0.3.0.tar.gz

  - folder: subprojects/tblite/subprojects/dftd4/subprojects/multicharge
    sha256: 953e2ace2f4035b1fa8ecf680f90b5ce6ad5caae17c8d8ccbc2578b92b69d3e7
    url: https://github.com/grimme-lab/multicharge/archive/v0.2.0.tar.gz

  - folder: subprojects/tblite/subprojects/s-dftd3
    sha256: 4bef311f8e5a2c32141eddeea65615c3c8480f917cd884488ede059fb0962a50
    url: https://github.com/awvwgk/simple-dftd3/archive/v0.6.0.tar.gz

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex
    - cp -r ${SRC_DIR}/subprojects/test-drive ${SRC_DIR}/subprojects/toml-f/subprojects/test-drive
    - export FFLAGS="${FFLAGS} -ffree-line-length-none"
    - |
      cmake ${CMAKE_ARGS} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DWITH_TESTS=OFF \
            -B build_dir \
            -GNinja
    - cmake --build build_dir
    - cmake --install build_dir

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - libblas
    - liblapack
  run:
    - xtb

test:
  commands:
    - crest --version

about:
  home: https://crest-lab.github.io/crest-docs/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING  # LGPL-3.0-or-later
    - COPYING.LESSER
    - subprojects/toml-f/LICENSE-Apache  # Apache-2.0 or MIT
    - subprojects/toml-f/LICENSE-MIT
    - subprojects/gfnff/COPYING  # LGPL-3.0-or-later
    - subprojects/gfnff/COPYING.LESSER
    - subprojects/gfn0/COPYING  # LGPL-3.0-or-later
    - subprojects/gfn0/COPYING.LESSER
    - subprojects/lwoniom/COPYING  # LGPL-3.0-or-later
    - subprojects/lwoniom/COPYING.LESSER
    - subprojects/test-drive/LICENSE-Apache  # Apache-2.0 or MIT
    - subprojects/test-drive/LICENSE-MIT
    - subprojects/tblite/COPYING  # LGPL-3.0-or-later
    - subprojects/tblite/COPYING.LESSER
    - subprojects/tblite/subprojects/mctc-lib/LICENSE  # Apache-2.0
    - subprojects/tblite/subprojects/dftd4/COPYING  # LGPL-3.0-or-later
    - subprojects/tblite/subprojects/dftd4/COPYING.LESSER
    - subprojects/tblite/subprojects/dftd4/subprojects/mstore/LICENSE  # Apache-2.0
    - subprojects/tblite/subprojects/dftd4/subprojects/multicharge/LICENSE  # Apache-2.0
    - subprojects/tblite/subprojects/s-dftd3/COPYING  # LGPL-3.0-or-later
    - subprojects/tblite/subprojects/s-dftd3/COPYING.LESSER
  summary: 'Conformer-Rotamer Ensemble Sampling Tool based on the xtb Semiempirical Extended Tight-Binding Program Package'
  description: |
    This is the official repository of the CREST. The program was
    originally developed by the Grimme group at the University of Bonn
    as is an extension to the xtb program to drive semiempirical quantum
    mechanical calculations for the exploration of chemical space.
    Since then several functionalities have been added to the code. 
    In its current state, the program provides a variety of sampling 
    procedures, for example for improved thermochemistry, or explicit solvation 
    and analysis of structure ensembles. 
  doc_url: https://crest-lab.github.io/crest-docs/
  dev_url: https://github.com/crest-lab/crest

extra:
  recipe-maintainers:
    - awvwgk
    - jan-janssen
