conda_forge_output_validation: true
bot:
  automerge: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
